import type { Metadata, Viewport } from "next";
import { Playfair_Display, Manrope } from "next/font/google";
import { notFound } from "next/navigation";
import { getDict } from "@/lib/content";
import { SITE_URL, isLocale, locales, type Locale } from "@/lib/site";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { OrganizationJsonLd } from "@/components/seo/JsonLd";
import "../globals.css";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin", "latin-ext", "cyrillic"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin", "latin-ext", "cyrillic"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800"],
});

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const viewport: Viewport = {
  themeColor: "#491522",
  width: "device-width",
  initialScale: 1,
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  const t = getDict(locale);

  return {
    metadataBase: new URL(SITE_URL),
    title: {
      default: t.meta.title,
      template: `%s | NUTRIWAY`,
    },
    description: t.meta.description,
    keywords: [...t.meta.keywords],
    applicationName: "NUTRIWAY",
    authors: [{ name: "NUTRIWAY NATURAL" }],
    creator: "NUTRIWAY NATURAL",
    publisher: "NUTRIWAY NATURAL",
    alternates: {
      canonical: `${SITE_URL}/${locale}`,
      languages: {
        uz: `${SITE_URL}/uz`,
        ru: `${SITE_URL}/ru`,
        "x-default": `${SITE_URL}/uz`,
      },
    },
    openGraph: {
      type: "website",
      siteName: "NUTRIWAY NATURAL",
      locale: t.meta.locale,
      url: `${SITE_URL}/${locale}`,
      title: t.meta.title,
      description: t.meta.description,
      // Preview image is generated by app/[locale]/opengraph-image.tsx.
    },
    twitter: {
      card: "summary_large_image",
      title: t.meta.title,
      description: t.meta.description,
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
        "max-video-preview": -1,
      },
    },
    category: "health",
  };
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();

  const typedLocale: Locale = locale;
  const t = getDict(typedLocale);

  return (
    <html
      lang={typedLocale}
      className={`${playfair.variable} ${manrope.variable} h-full`}
    >
      <body className="flex min-h-full flex-col antialiased">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-[var(--radius-sm)] focus:bg-wine-800 focus:px-5 focus:py-3 focus:text-bone-50"
        >
          {typedLocale === "uz"
            ? "Asosiy qismga o'tish"
            : "Перейти к содержимому"}
        </a>

        <Header locale={typedLocale} t={t} />
        <main id="main" className="flex-1">
          {children}
        </main>
        <Footer locale={typedLocale} t={t} />

        <OrganizationJsonLd locale={typedLocale} />
      </body>
    </html>
  );
}
